### ISSUE TITLE
Keyboard displays over formula when running on mobile

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#409] opened 2023-04-12 17:07 UTC
### Description

Steps to reproduce:
1) Launch sinerider on an Android handset (tested with a Samsung Galaxy S23)
2) Click on the formula.
Expected behavior: Allows for the editing of the formula
Actual behavior: Keyboard displays above formula, preventing you from seeing what you're editing.

**Comment by karamassie** [comment] 2023-04-13 16:51
mobile generally needs a whole UI review and pass.

**Comment by polypixeldev** [comment] 2023-04-15 03:08
can't reproduce this issue on samsung galaxy a20, firefox

**Comment by karamassie** [comment] 2023-04-16 23:55
yeh i had no problem either. closing.

**Closed by karamassie** 2023-04-16 23:55 UTC
Labels: bug, mobile support
