### ISSUE TITLE
[FEATURE] Create final credits scene

### ISSUE THREAD

**Issue by camdan-me** [hackclub/sinerider#462] opened 2023-05-01 06:23 UTC
### Description

Self-explanatory

**Comment by alhardwarehyde** [comment] 2023-05-01 17:25
@camdan-me is this a dupe of #233 ?

**Comment by camdan-me** [comment] 2023-05-01 17:27
No, referring to the actual game credits

**Comment by alhardwarehyde** [comment] 2023-05-01 17:43
Ah, credits exist in Figma, just need to be added to the game. @ClaireBookworm

**Comment by ClaireBookworm** [comment] 2023-05-01 20:32
How do I add / should I send it to someone?

**Comment by camdan-me** [comment] 2023-05-02 05:30
Is the file public? You can link it here and someone can self-assign.

**Comment by karamassie** [comment] 2023-05-04 23:05
i just played this, and it seems done unless there was an update

**Comment by karamassie** [comment] 2023-05-05 23:05
@polytroper pls ensure @ClaireBookworm 's latest credit file is swapped in

**Comment by ClaireBookworm** [comment] 2023-05-05 23:06
Will send the webp in a bit

**Closed** 2023-05-08 02:50 UTC
Labels: enhancement
