### ISSUE TITLE
Level One: Add Windmill

### ISSUE THREAD

**Issue by Hugoyhu** [hackclub/sinerider#97] opened 2022-07-18 16:23 UTC
make spinny windmill in back left corner if there’s time (file in folder)

**Comment by karamassie** [comment] 2022-08-23 16:33
@ClaireBookworm can you link the windmill art asset pls

**Comment by ClaireBookworm** [comment] 2022-08-24 00:40
Here! https://drive.google.com/drive/u/0/folders/1-57cj8MDsw7A1URPr3ZfArzlyAerLSg3

**Comment by karamassie** [comment] 2022-08-24 18:50
dupe of #134

**Closed by karamassie** 2022-08-24 18:50 UTC
Labels: art tech
