### ISSUE TITLE
Autozoom could be better

### ISSUE THREAD

**Issue by grymmy** [hackclub/sinerider#191] opened 2023-03-06 20:59 UTC
### Description

This is a nit-pick, really - I encountered a situation where it seemed clear to me that the autozoom wasn't filling up the screen as well as it possibly could (I think).  If this isn't an error or there's a good reason for this that I'm not aware of, please close/wontfix...  Hopefully the screenshot is self-explanatory enough.

### Screenshots

<img width="1918" alt="Screenshot 2023-03-06 at 3 55 57 PM" src="https://user-images.githubusercontent.com/43505167/223229215-97709d38-a203-44ce-9056-8470d386ae06.png">

**Comment by karamassie** [comment] 2023-03-15 21:07
good catch. closing as a dupe of #196

**Closed by karamassie** 2023-03-15 21:07 UTC
Labels: bug
